name: Test
on:
  pull_request: {}
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.12
          - 1.13
          - 1.14
          - 1.15
          - 1.16
          - 1.17
          - 1.18
          - 1.19
          - 1.20
          - 1.21
          - 1.22
          - 1.23
    name: Go ${{ matrix.go }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
        id: go
      - name: Get dependencies
        run: go get -t -v ./...
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@v0.2.2
      - name: Lint
        run: staticcheck -checks=all ./...
      - name: Test
        run: go test -v -race ./...
